version: "3.7"
services:
  node:
    image: sdc-node
    container_name: sdc-node
    depends_on:
      - postgres
    ports:
      - 3500:1234
    build:
      context: .
      dockerfile: node.Dockerfile
  postgres:
    image: sdc-postgres
    container_name: sdc-postgres
    ports:
    - 3002:5432
    environment:
      POSTGRES_PASSWORD: sdc4321
    build:
      context: .
      dockerfile: postgres.Dockerfile